#!/bin/bash
set -x
if test $# = 0
then
	/usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf
else
	service postgresql start
	"$@"
fi
